---
- name: Check ha status 
  bigip_command:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    commands:
      - show cm sync-status
    wait_for:
      - result[0] contains "high-availability"
    match: all
    interval: 2
    retries: 10
  delegate_to: localhost
...
